### ISSUE TITLE
Suggestions & Fix Bugs

### ISSUE THREAD

**Issue by Ritanium** [PgerTools/MSMC-Inbox#2]
### Suggestion
- Make the valid mails target check add to a file instead of discord webhook

### Fix Bug
- When this tool find hit, it pop up an error message in MSMC

**Comment by Ritanium** [comment]
Error: https://prnt.sc/DWgwPREFhapV

**Comment by PgerTools** [comment]
Thank you for your suggestion! 
This has already been added in the latest version of Inboxer.

As for your bug report I could not recreate this error and it is working fine for me.
Please make sure you are using the latest version of MSMC and Inboxer.

**Comment by Ritanium** [comment]
> Thank you for your suggestion! This has already been added in the latest version of Inboxer.
> 
> As for your bug report I could not recreate this error and it is working fine for me. Please make sure you are using the latest version of MSMC and Inboxer. Also make sure you have followed the instructions for setting up Inboxer correctly there is a detailed video if you need help!

Thanks you, I will retry install the latest version of MSMC and Inboxer and see if the error still shows
