### ISSUE TITLE
LOGIN FAILED ON IMAP 

### ISSUE THREAD

**Issue by pyp** [PgerTools/MSMC-Inbox#7]
hello, r u also getting Failed to login or fetch emails: b'LOGIN failed.' when trying to login to an outlook via your IMAP server code?

**Comment by zunknown2** [comment]
fucking stupid dumbass nigga that fucking means the account password its wrong fucking idiot btw imap doesnt work anymore stupid hoe

**Comment by pyp** [comment]
my bad for asking a question

atleast I don't make fake FBI taken down websites to try to impress my friends at school like you do lil nigga
